version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - lana-pharmacy
    volumes:
      - type: bind
        source: $HOST/home/waleed/hdd/mongo-db/data
        target: /data/db
      - type: bind
        source: $HOST/home/waleed/hdd/mongo-db/configdb
        target: /data/configdb
  spring:
    build: ./be-v2
    container_name: pharmacy-be
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - lana-pharmacy
  angular:
    build: ./frontend
    container_name: pharmacy-fe
    ports:
        - '90:80'
    depends_on:
        - spring
    networks:
      - lana-pharmacy
networks:
    lana-pharmacy:
        driver: bridge
volumes:
    mongo-data:
